apiVersion: apps/v1
kind: Deployment
metadata:
  name: appwrite-redis
spec:
  selector:
    matchLabels:
      app: appwrite-redis
  template:
    metadata:
      labels:
        app: appwrite-redis
    spec:
      containers:
        - image: redis:6.0-alpine3.12
          name: appwrite-redis
          volumeMounts:
            - mountPath: /data
              name: appwrite-redis
      volumes:
        - name: appwrite-redis
          persistentVolumeClaim:
            claimName: appwrite-redis

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: appwrite-redis
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---

apiVersion: v1
kind: Secret
metadata:
  name: appwrite-redis
stringData:
  _APP_REDIS_HOST: appwrite-redis
  _APP_REDIS_PORT: "6379"
  #_APP_REDIS_USER: appwrite
  #_APP_REDIS_PASS: "@ppWR1te"

---

apiVersion: v1
kind: Service
metadata:
  name: appwrite-redis
spec:
  selector:
    app: appwrite-redis
  ports:
  - port: 6379
