apiVersion: apps/v1
kind: Deployment
metadata:
  name: appwrite-realtime
spec:
  selector:
    matchLabels:
      app: appwrite-realtime
  template:
    metadata:
      annotations:
        traefik.constraint-label-stack: appwrite
        traefik.docker.network: appwrite
        traefik.enable: "true"
        traefik.http.routers.appwrite_realtime_ws.entrypoints: appwrite_web
        traefik.http.routers.appwrite_realtime_ws.rule: PathPrefix(`/v1/realtime`)
        traefik.http.routers.appwrite_realtime_ws.service: appwrite_realtime
        traefik.http.routers.appwrite_realtime_wss.entrypoints: appwrite_websecure
        traefik.http.routers.appwrite_realtime_wss.rule: PathPrefix(`/v1/realtime`)
        traefik.http.routers.appwrite_realtime_wss.service: appwrite_realtime
        traefik.http.routers.appwrite_realtime_wss.tls: "true"
        traefik.http.routers.appwrite_realtime_wss.tls.certresolver: dns
        #traefik.http.services.appwrite_realtime.loadbalancer.server.port: "80"
      labels:
        app: appwrite-realtime
    spec:
      containers:
        - command:
            - realtime
          image: appwrite/appwrite:0.10.4
          name: appwrite-realtime
          envFrom:
          - configMapRef:
              name: appwrite
          - secretRef:
              name: appwrite-mariadb 
          - secretRef:
              name: appwrite-redis
