apiVersion: v1
kind: Secret
metadata:
  name: appwrite-influxdb
stringData:
  _APP_INFLUXDB_HOST: appwrite-influxdb
  _APP_INFLUXDB_PORT: "8086"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: appwrite-influxdb
spec:
  selector:
    matchLabels:
      app: appwrite-influxdb
  template:
    metadata:
      labels:
        app: appwrite-influxdb
    spec:
      containers:
        - image: appwrite/influxdb:1.0.0
          name: appwrite-influxdb
          volumeMounts:
            - mountPath: /var/lib/influxdb
              name: appwrite-influxdb
      volumes:
        - name: appwrite-influxdb
          persistentVolumeClaim:
            claimName: appwrite-influxdb

---

apiVersion: v1
kind: Service
metadata:
  name: appwrite-influxdb
spec:
  selector:
    app: appwrite-influxdb
  ports:
  - port: 8086

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: appwrite-influxdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
