apiVersion: apps/v1
kind: Deployment
metadata:
  name: appwrite-mariadb
spec:
  selector:
    matchLabels:
      app: appwrite-mariadb
  template:
    metadata:
      labels:
        app: appwrite-mariadb
    spec:
      containers:
        - args:
            - mysqld
            - --innodb-flush-method=fsync
          env:
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                key: _APP_DB_SCHEMA
                name: appwrite-mariadb
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                key: _APP_DB_USER
                name: appwrite-mariadb         
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: _APP_DB_PASS
                name: appwrite-mariadb         
          envFrom:
          - secretRef:
              name: appwrite-mariadb-root 
          image: appwrite/mariadb:1.2.0
          name: appwrite-mariadb
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: appwrite-mariadb
      volumes:
        - name: appwrite-mariadb
          persistentVolumeClaim:
            claimName: appwrite-mariadb

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: appwrite-mariadb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---

apiVersion: v1
kind: Secret
metadata:
  name: appwrite-mariadb
stringData:
  _APP_DB_HOST: appwrite-mariadb
  _APP_DB_PORT: "3306"
  _APP_DB_SCHEMA: appwrite
  _APP_DB_USER: appwrite
  _APP_DB_PASS: "@appWR1te"

---

apiVersion: v1
kind: Secret
metadata:
  name: appwrite-mariadb-root
stringData:
  MYSQL_ROOT_PASSWORD: "root@appWR1te"

---

apiVersion: v1
kind: Service
metadata:
  name: appwrite-mariadb
spec:
  selector:
    app: appwrite-mariadb
  ports:
  - port: 3306

